import './globals.css'
import { Koulen } from 'next/font/google'
import {Analytics} from '@vercel/analytics/react';

const koulen = Koulen({weight: ['400'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={koulen.className}>
				{children}
				<Analytics />
			</body>
    </html>
  )
}
